#   Autor: Pedro Igor Martins dos Reis
#   Data: 29/12/2021
#   Arquivo: ".bash_profile"

[ -f $HOME/.bashrc ] && . $HOME/.bashrc

# XDG
export XDG_SESSION_TYPE=wayland
export XDG_CURRENT_DESKTOP=wayfire

# QT
export QT_QPA_PLATFORMTHEME=qt5ct
export QT_QPA_PLATFORM=wayland-egl

# Firefox
export MOZ_ENABLE_WAYLAND=1
export MOZ_DISABLE_RDD_SANDBOX=1

# JAVA
export _JAVA_AWT_WM_NONREPARENTING=1
export JAVA_FONTS=/usr/share/fonts/google-noto/
export JDK_JAVA_OPTIONS='-Dsun.java2d.opengl=true'
export _JAVA_OPTIONS='-Dswing.aatext=true -Dawt.useSystemAAFontSettings=on -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel'
